# Site Settings

# paginate:            5

# Build settings
markdown:            kramdown # use <TAG markdown="1"> to render markdown within HTML tags!
highlighter:         rouge
permalink:           /blog/:title.html #none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed]

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#   path:	     rss-feed.xml
