title: Travis W. Peters
tagline: all things work and play
description: A website dedicated to my academic work, hobbies, and other ramblings.
author: Travis Peters

#
# Personal Settings
#
url: https://traviswp.github.io/
baseurl:
avatar: profile.png
email: traviswp@cs.dartmouth.edu
# traviswp@gmail.com
# traviswpeters@protonmail.com
# travis.w.peters.gr@dartmouth.edu

handles:
  github: traviswpeters
  gitlab: traviswpeters
  linkedin: traviswpeters # old: travis-peters-3513512a
  twitter: traviswpeters
  facebook: travis.william.peters # old: travis.peters.144
  instagram: the.travisaurus.rex # traviswpeters
  strava: traviswpeters
  keybase: traviswpeters
  quora: Travis-Peters
  stackoverflow: users/2276247/traviswp
  orcid: 0000-0003-0072-2735 # --> suggested HTML: <div itemscope itemtype="https://schema.org/Person"><a itemprop="sameAs" content="https://orcid.org/0000-0003-0072-2735" href="https://orcid.org/0000-0003-0072-2735" target="orcid.widget" rel="noopener noreferrer" style="vertical-align:top;"><img src="https://orcid.org/sites/default/files/images/orcid_16x16.png" style="width:1em;margin-right:.5em;" alt="ORCID iD icon">orcid.org/0000-0003-0072-2735</a></div>

# -> Available social icons are powered by Font Awesome, so you can use any icon that they offer
# - {icon: '', type: '', link: ''}
social:
- {icon: 'envelope', type: 's', link: 'mailto:traviswp@cs.dartmouth.edu'}
- {icon: 'github',  type: 'b', link: 'https://www.github.com/traviswpeters'}
# - {icon: 'gitlab', type: 'b', link: 'https://gitlab.cs.dartmouth.edu/traviswpeters'}
- {icon: 'linkedin',  type: 'b', link: 'https://www.linkedin.com/in/traviswpeters'}
- {icon: 'twitter',  type: 'b', link: 'https://twitter.com/traviswpeters'}
- {icon: 'facebook',  type: 'b', link: 'https://www.facebook.com/travis.william.peters'}
- {icon: 'instagram',  type: 'b', link: 'https://www.instagram.com/the.travisaurus.rex'}
- {icon: 'strava',  type: 'b', link: 'https://www.strava.com/athletes/traviswpeters'}
# - {icon: 'keybase', type: 'b', link: 'https://keybase.io/traviswpeters'}
# - {icon: 'quora', type: 'b', link: 'https://www.quora.com/profile/Travis-Peters'}
# - {icon: 'stack-overflow', type: 'b', link: 'https://stackoverflow.com/users/2276247/traviswp'}
# - {icon: 'orcid', type: 'b', link: 'https://orcid.org/0000-0003-0072-2735'}
# - {icon: 'rss-square', link: 'feed.xml'}

#
# Site Menus
#
menu:
- {name: 'Home', url: ''}
- {name: 'Teaching', url: 'teaching.html'}
- {name: 'Research', url: 'research.html'}
- {name: 'CV', url: 'vita.pdf'}
- {name: 'R&eacute;sum&eacute;', url: 'resume.pdf'}
- {name: 'News', url: 'news.html'}
- {name: 'Misc.', url: 'misc.html'}

# funmenu:
# - {name: 'Resources', url: 'resources.html'}
# - {name: 'Projects', url: 'projects.html'}
# - {name: 'Running', url: 'running.html'}
# - {name: 'Blog', url: 'blog.html'}

#
# Change to true for Disqus comments
#
# disqus:
#   comments: false
#   disqus_shortname: 'https-travispeters-github-io'

google-ID: 'CHANGEME' #'UA-80213386-1'
