title: Travis Peters
author: Travis Peters
avatar: profile.png
description: A website dedicated to my academic work, hobbies, and other ramblings.
school: "Montana State University"
email: "travis.peters1@montana.edu"
# traviswp@gmail.com
# traviswpeters@protonmail.com
# travis.w.peters.gr@dartmouth.edu
# traviswp@cs.dartmouth.edu
office: "NAH 253A"
officehours: "M/W/F 9:00&ndash;10:00 a.m." # and by appointment.
officephone: "‭406-994-4296‬"
officephoneext: "x4296" # extension
url: https://traviswpeters.github.io/
githuburl: https://github.com/traviswpeters/traviswpeters.github.io

# Site Menus
menu:
- {name: 'Home', url: ''}
- {name: 'Teaching', url: '#teaching'}
- {name: 'Publications', url: '#publications'}
- {name: 'Activities', url: '#activities'}
- {name: 'Awards', url: '#awards'}
- {name: 'News', url: '#news'}
- {name: 'CV', url: 'vita.pdf'}
- {name: 'Docs', url: ''}
# - {name: 'CV (web)', url: 'vita.html'}
# - {name: 'R&eacute;sum&eacute;', url: 'resume.pdf'}
# - {name: 'Misc.', url: 'misc.html'}

docs:
- name: 'CV (pdf)'
  url: vita.pdf
# - name: 'CV (web)'
#   url: vita.html
- name: 'R&eacute;sum&eacute; (pdf)'
  url: resume.pdf
# - name: 'Bib (web)'
#   url: bib.html
- name: 'MSU Application Materials (pdf)'
  url: travis-peters-dartmouth-msu.pdf

handles:
  github: traviswpeters
  gitlab: traviswpeters
  linkedin: traviswpeters # old: travis-peters-3513512a
  twitter: traviswpeters
  facebook: travis.william.peters # old: travis.peters.144
  instagram: the.travisaurus.rex # traviswpeters
  strava: traviswpeters
  keybase: traviswpeters
  quora: Travis-Peters
  stackoverflow: users/2276247/traviswp
  orcid: 0000-0003-0072-2735 # --> suggested HTML: <div itemscope itemtype="https://schema.org/Person"><a itemprop="sameAs" content="https://orcid.org/0000-0003-0072-2735" href="https://orcid.org/0000-0003-0072-2735" target="orcid.widget" rel="noopener noreferrer" style="vertical-align:top;"><img src="https://orcid.org/sites/default/files/images/orcid_16x16.png" style="width:1em;margin-right:.5em;" alt="ORCID iD icon">orcid.org/0000-0003-0072-2735</a></div>

# -> Available social icons are powered by Font Awesome, so you can use any icon that they offer
# - {icon: '', type: '', link: ''}
social:
- {icon: 'envelope', type: 's', link: 'mailto:travis.peters1@gmontana.edu'}
- {icon: 'github',  type: 'b', link: 'https://www.github.com/traviswpeters'}
# - {icon: 'gitlab', type: 'b', link: 'https://gitlab.cs.dartmouth.edu/traviswpeters'}
- {icon: 'linkedin',  type: 'b', link: 'https://www.linkedin.com/in/traviswpeters'}
- {icon: 'twitter',  type: 'b', link: 'https://twitter.com/traviswpeters'}
- {icon: 'facebook',  type: 'b', link: 'https://www.facebook.com/travis.william.peters'}
- {icon: 'instagram',  type: 'b', link: 'https://www.instagram.com/the.travisaurus.rex'}
- {icon: 'strava',  type: 'b', link: 'https://www.strava.com/athletes/traviswpeters'}
# - {icon: 'keybase', type: 'b', link: 'https://keybase.io/traviswpeters'}
# - {icon: 'quora', type: 'b', link: 'https://www.quora.com/profile/Travis-Peters'}
# - {icon: 'stack-overflow', type: 'b', link: 'https://stackoverflow.com/users/2276247/traviswp'}
# - {icon: 'orcid', type: 'b', link: 'https://orcid.org/0000-0003-0072-2735'}
# - {icon: 'rss-square', link: 'feed.xml'}


google-ID: 'CHANGEME' #'UA-80213386-1'
