title: Travis Peters
tagline: all things work and play
description: A website dedicated to my academic work, hobbies, and other ramblings.
author: Travis Peters

#
# Personal Settings
#
url: https://traviswp.github.io/
baseurl:
avatar: profile.png
email: traviswp@cs.dartmouth.edu

# github: traviswp
# linkedin: travis-peters-3513512a
# twitter: traviswpeters
# facebook: travis.peters.144
# instagram: the.travisaurus.rex
# strava: traviswpeters
# gitlab: traviswpeters
# stackoverflow: username   #e.g: users/2735833/proton1h1

social:
- {icon: 'envelope', link: 'mailto:traviswp@cs.dartmouth.edu'}
- {icon: 'github', link: 'https://www.github.com/traviswp'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/travis-peters-3513512a'}
- {icon: 'twitter', link: 'https://twitter.com/traviswpeters'}
- {icon: 'facebook-square', link: 'https://www.facebook.com/travis.peters.144'}
- {icon: 'instagram', link: 'https://www.instagram.com/the.travisaurus.rex'}
- {icon: 'road', link: 'https://www.strava.com/athletes/traviswpeters'}
- {icon: 'gitlab', link: 'https://gitlab.cs.dartmouth.edu/traviswpeters'}
#- {icon: 'rss-square', link: 'feed.xml'}
# -> Available social icons are powered by Font Awesome, so you can use any icon that they offer

#
# Site Menus
#
menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Research', path: 'menu', url: 'research.html'}
- {name: 'CV', path: 'menu', url: 'cv.html'}
- {name: 'News', path: 'menu', url: 'news.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'} #Blog

#
# Change to true for Disqus comments
#
disqus:
  comments: false
  disqus_shortname: 'https-travispeters-github-io'
  # disqus_shortname: 'https-lenpaul-github-io-lagrange'

google-ID: 'CHANGEME' #'UA-80213386-1'
